python uncertainty_computation.py \
    --output_dir=./saved_models \
    --model_type=starcoder3b \
    --tokenizer_name=/home/rsr200002/LLMs/StarCoder2_3B \
    --model_name_or_path=/home/rsr200002/LLMs/StarCoder2_3B \
    --do_train \
    --train_data_file=../dataset/train.jsonl \
    --eval_data_file=../dataset/dev.jsonl \
    --test_data_file=../dataset/test.jsonl \
    --epoch 5 \
    --project vul \
    --block_size 512 \
    --train_batch_size 4 \
    --eval_batch_size 4 \
    --learning_rate 2e-5 \
    --max_grad_norm 1.0 \
    --evaluate_during_training \
    --seed 123456  2>&1 | tee train.log